apiVersion: v1
kind: Service
metadata:
  labels:
    name: web-service
  name: web-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: web-container
  type: LoadBalancer
